###                               HW1 Programming Assignment

1. Because $C$ is a subspace of the nullspace of $H$, which is a full rank matrix on $F_2^((n-k)×n)$, the dimension of $C$ is equal to the number of free variable, which is $n-(n-k)=k$. So, $C$ is a $n×k$ matrix. 
  
 Given $C$, H isn’t unique.  

2. The cardinality of $R(H)$ is equal to the rank of $H$, which is $(n-k)$. 

3. After testing with my checkCodeword function, the answer of $X_1,X_2,X_3$ is:  
    False;	True; 	False. 


In [5]:
import numpy as np
#------------------3
def bidot(a,b):
    temp=np.dot(a,b)
    for i in range(temp.shape[0]):
        temp[i]=temp[i]%2
    return temp


def checkCodeword(H,X):
    result=bidot(H,X)
    for i in range(result.shape[0]):
        if result[i]!=0:
            return False
    return True

H_test=np.mat([[1,0,0,0,1,1,1,0,0,0,1,1,1,0,1],
          [0,1,0,0,1,0,0,1,1,0,1,1,0,1,1],
          [0,0,1,0,0,1,0,1,0,1,1,0,1,1,1],
          [0,0,0,1,0,0,1,0,1,1,0,1,1,1,1]])
X1=np.mat([1,1,1,1,1,1,1,0,0,1,0,0,0,0,0])
X2=np.mat([1,0,0,1,1,0,0,1,0,1,0,0,0,0,0])
X3=np.mat([1,0,0,0,1,0,0,0,0,0,0,0,0,0,1])

print(checkCodeword(H_test,X1.T))
print(checkCodeword(H_test,X2.T))
print(checkCodeword(H_test,X3.T))

False
True
False


4. The $E$ is:  
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]  
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]  
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]  
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]  
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]  
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]  
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]  
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]  
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]    
    For $H$ in 3., the $S$ is:  
[[0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1.]  
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1.]  
 [0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1.]  
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1.]]

In [6]:
#--------------------------4
def buildTable(H):
    n=H.shape[1]
    E=np.eye(n)
    z=np.zeros(n)
    E=np.c_[z.T,E]
    S=bidot(H,E)
    return E,S

print("The E is: \n{}".format(buildTable(H_test)[0]))
print("For H in 3., the S is: \n{}".format(buildTable(H_test)[1]))

The E is: 
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
For H in 3., the S is: 
[[0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1.]
 [0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1.

5. 	I recalculated the syndrome vector of every vector $e$ and compared the result with $S$ generated in 4. and got the following result:  

In [7]:
#--------------------------5
n=H_test.shape[1]
E=np.eye(n)
z=np.zeros(n)
E=np.c_[z.T,E]
testM=np.mat(bidot(H_test,E))
computeM=buildTable(H_test)[1]
for i in range(testM.shape[1]):
    if ((testM.T)[i]==(computeM.T)[i]).all():
        print(" The syndrome vector {} of {} is in S.".format(testM.T[i],E.T[i]))

 The syndrome vector [[0. 0. 0. 0.]] of [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] is in S.
 The syndrome vector [[1. 0. 0. 0.]] of [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] is in S.
 The syndrome vector [[0. 1. 0. 0.]] of [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] is in S.
 The syndrome vector [[0. 0. 1. 0.]] of [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] is in S.
 The syndrome vector [[0. 0. 0. 1.]] of [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] is in S.
 The syndrome vector [[1. 1. 0. 0.]] of [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] is in S.
 The syndrome vector [[1. 0. 1. 0.]] of [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] is in S.
 The syndrome vector [[1. 0. 0. 1.]] of [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] is in S.
 The syndrome vector [[0. 1. 1. 0.]] of [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] is in S.
 The syndrome vector [[0. 1. 0. 1.]] of [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] is in S.
 The syndrome vector [[0. 0. 1. 1.]] of 

6. (a) I wrote the channelDecode function, the method is to compare the result of $H*E$ with syndrome matrix $S$, and get the $e$ and estimated $x$, the code is as below. I test the function with $X2$ given in 3. and $e=[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0]$, the test result is as below.

In [8]:
#-----------------------6(a)
def channelDecode(r):
    hr=bidot(H_test,r.T)
    table_E=buildTable(H_test)[0].T
    table_S=buildTable(H_test)[1].T
    e_estimate=[]
    for i in range(table_S.shape[0]):
        if (hr.T==table_S[i]).all():
            e_estimate=table_E[i]
    x=abs(r-e_estimate)
    return e_estimate,x
X4=(X2+[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0])%2
print("The smallest l1-norm e is: \n{}".format(channelDecode(X4)[0]))
print("The estimated x is: \n{}".format(channelDecode(X4)[1]))

The smallest l1-norm e is: 
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
The estimated x is: 
[[1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]]


6. (b) All possible received signals with 1 bit error are as below:  
 [[1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]  
 [0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]  
 [1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]  
 [1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]  
 [1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]  
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]  
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]  
 [1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]  
 [1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]  
 [1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]  
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]  
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]  
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]  
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]  
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]  
With given X, the success times are: 16.  
I tried X2 given in 3., and the success times are: 16. 

In [9]:
#-----------------------6(b)
X_test=np.mat([1,1,1,1,1,0,0,0,0,1,0,0,0,0,0])

def add_error(X):
    error_1bit=buildTable(H_test)[0].T
    X_error=(error_1bit+X)%2
    return X_error

X_error=add_error(X_test)
print("All possible received signals with 1 bit error are as below: \n {}".format(X_error))

def suctimes(Xwitherror,X):
    Stimes=0
    for i in range(Xwitherror.shape[0]):
        X_decode=channelDecode(Xwitherror[i])[1]
        if (X_decode==X).all():
            Stimes=Stimes+1
    return Stimes
print("With given X, the success times are: {}".format(suctimes(X_error,X_test)))

X_error1=add_error(X2)
print("With X2 given in 3., the success times are: {}".format(suctimes(X_error1,X2)))

All possible received signals with 1 bit error are as below: 
 [[1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]
With given X, the success times are: 16
With X2 given in 3., the success times are: 16


6. (c) I generated all possible received signals with 2 bits error, and used the smallest l1-norm method to decode, the number of successes is 0.  
   I guess with 3 bits error, the success time should be 0, too. Then I generated all possible received signals with 3 bits error to test, the result is indeed 0.    
   I think this problem can be generalized to all $Ax=b$ problems. When A satisfies some certain conditions (such as H given in this question), this system of equations can have more than one, even infinite solutions. When we only consider a single solution, for example, the smallest l1- In norm, only one set of solutions can be obtained. In this question, it is more like the basis of other solutions, which can span to other solutions. And there are more solutions that are linear combinations of the solutions we get, so we cannot get the correct answers in 2 bit and 3 bit problems. 

In [68]:
#-------------------------6(c)
from itertools import combinations
def add_2biterror(X):
    n=H_test.shape[1]
    error_2bit=np.zeros([105,n])
    X_count=np.arange(0,n,1)
    L=list(combinations(X_count,2))
    for i in range(105):
        error_2bit[i][L[i][0]]=1
        error_2bit[i][L[i][1]]=1
    X_2biterror=(error_2bit+X)%2
    return X_2biterror
X_with2biterror=add_2biterror(X_test)
print(X_with2biterror)
print("The number of possible received signals is {}".format(X_with2biterror.shape[0]))
print("With 2 bit error in X, the success times of smallest l1-norm are: {}".format(suctimes(X_with2biterror,X_test)))

[[0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 1. 1. 0.]
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 0. 1. 1.]]
The number of possible received signals is 105
With 2 bit error in X, the success times of smallest l1-norm are: 0


In [67]:
def add_3biterror(X):
    n=H_test.shape[1]
    error_3bit=np.zeros([455,n])
    X_count=np.arange(0,n,1)
    L=list(combinations(X_count,3))
    for i in range(455):
        error_3bit[i][L[i][0]]=1
        error_3bit[i][L[i][1]]=1
        error_3bit[i][L[i][2]]=1
    X_3biterror=(error_3bit+X)%2
    return X_3biterror
X_with3biterror=add_3biterror(X_test)
print(X_with3biterror)
print("The number of possible received signals is {}".format(X_with3biterror.shape[0]))
print("With 3 bit error in X, the success times of smallest l1-norm are: {}".format(suctimes(X_with2biterror,X_test)))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 1. ... 0. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
The number of possible received signals is 455
With 3 bit error in X, the success times of smallest l1-norm are: 0
